console.log("EXERCISES 2")
console.log(`10 + 24 = ${10 + 24}`)
console.log(`"10" + "24" = ${"10" + "24"}`)
console.log(`"Hello" + " " + 2021 = ${"Hello" + " " + 2021}`)
console.log(`1 + 2 * 3 = ${1 + 2 * 3}`)
console.log(`(1 + 3) ** 2 = ${(1 + 3) ** 2}`)
console.log(`1 / 0 = ${1 / 0}`)
console.log(`6 % 2 = ${6 % 2}`)
console.log(`5.5 % 2 = ${5.5 % 2}`)
console.log(`Number("123") = ${Number("123")}`)
console.log(`typeof(1 + "") = ${typeof(1 + "")}`)
console.log(`5 == "5" = ${5 == "5"}`)
console.log(`5 === "5" = ${5 === "5"}`)
console.log(`8 != 8.0 = ${8 != 8.0}`)
console.log(`8 !== 8.0 = ${8 !== 8.0}`)
console.log(`"true" === true = ${"true" === true}`)
console.log(`4 <= 4.0 = ${4 <= 4.0}`)
console.log(`7 >= 7 = ${7 >= 7}`)
console.log(`true && true = ${true && true}`)
console.log(`true && false = ${true && false}`)
console.log(`true || true = ${true || true}`)
console.log(`false || true = ${false || true}`)
console.log(`!true = ${!true}`)
console.log(`!false = ${!false}`)
console.log(`false && (true || true) = ${false && (true || true)}`)
console.log(`false && true || true = ${false && true || true}`)